# Generated by Django 4.0.2 on 2022-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('email_address', models.EmailField(max_length=50, unique=True)),
                ('bvn', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('mother_name', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('local_govt_area', models.CharField(blank=True, max_length=50)),
                ('home_town', models.CharField(blank=True, max_length=50)),
                ('residential_address', models.CharField(max_length=100)),
                ('nok_name', models.CharField(max_length=50)),
                ('nok_address', models.CharField(max_length=100)),
                ('nok_number', models.IntegerField()),
                ('nok_email', models.EmailField(blank=True, max_length=50)),
                ('loan_amount', models.IntegerField()),
                ('tenor_in_weeks', models.IntegerField()),
                ('purpose', models.CharField(choices=[('PS', 'Postgraduate Study'), ('US', 'Undergraduate Study'), ('I', 'Immigration'), ('V', 'Vacation')], max_length=30)),
                ('destination', models.CharField(max_length=50)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('human_referral', models.CharField(blank=True, max_length=50)),
                ('id_card', models.ImageField(upload_to='file_upload')),
                ('utility', models.ImageField(upload_to='file_upload')),
                ('passport', models.ImageField(upload_to='file_upload')),
                ('referral_code', models.CharField(blank=True, max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
