# Generated by Django 4.0.2 on 2022-02-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('account_no', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='application_status',
            field=models.CharField(choices=[('Account Opening', 'Account Opening'), ('Account Funding', 'Account Funding'), ('Days to Maturity', 'Days to Maturity'), ('Funds Liquidated', 'Funds Liquidated')], default='Account Opening', max_length=30),
        ),
        migrations.AddField(
            model_name='apply',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aspire.account'),
        ),
    ]
